[project]
name = "delphiagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ag2[openai]>=0.9.6",
    "autogen>=0.9.6",
    "autogen-agentchat~=0.2",
]
